beamline_config:
  beam_energy: 0.06641461763347117
  pv_to_integrated_gradient: 1.0
  scan_quad_length: 0.1244
  scan_quad_pv: QUAD:HTR:120:BCTRL
  scan_quad_range:
  - -4.48035
  - 4.479
  transport_matrix_x:
  - - 1.0
    - 2.2
  - - 0.0
    - 1.0
  transport_matrix_y:
  - - 1.0
    - 2.2
  - - 0.0
    - 1.0
constants: {}
image_diagnostic:
  array_data_suffix: Image:ArrayData
  array_n_cols: Image:ArraySize0_RBV
  array_n_rows: Image:ArraySize1_RBV
  background_file: null
  bounding_box_half_width: 3.0
  min_log_intensity: 4.0
  n_fitting_restarts: 1
  resolution: RESOLUTION
  roi: null
  save_image_location: null
  screen_name: OTRS:HTR:330
  testing: true
  visualize: true
  wait_time: 1.0
minimum_log_intensity: 4.0
n_shots: 3
run_dir: .
secondary_observables:
- SOLN:GUNB:212:BCTRL
- SOLN:GUNB:823:BCTRL
- QUAD:GUNB:212:1:BCTRL
- QUAD:GUNB:212:2:BCTRL
- QUAD:GUNB:823:1:BCTRL
- QUAD:GUNB:823:2:BCTRL
- QUAD:HTR:120:BCTRL
- QUAD:HTR:140:BCTRL
- QUAD:HTR:300:BCTRL
- QUAD:HTR:320:BCTRL
- BEND:HTR:480:BACT
visualize: false
wait_time: 2.0
